# Generated by Django 5.0.2 on 2024-03-31 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_model',
            name='create_time',
        ),
    ]
