# Generated by Django 5.0.2 on 2024-02-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_model',
            name='called',
            field=models.CharField(choices=[("Bog'lanildi", 'Boglanildi'), ("Bog'lanilmadi", 'Boglanilmadi')], default="Bog'lanilmadi", max_length=100),
        ),
    ]
